<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="www/css/cocktails.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Mister Cocktail</title>
    <!-- Charger CSS de bootstrap, police Montserrat sur Google Fonts et le CSS de l'application -->
</head>
<body class="container-fluid">
    <nav>
        <a href="index.php">Accueil</a>
        <h1>Mister Cocktail</h1>
    </nav>

    <h2>Détails d'un cocktail</h2>
    <ul>
        <li>Nom :<?= $resCocktail['nom'];?></li>
        <li>Famille :<?= $resCocktail['nomFamille'];?></li>
        <li>Description : <p><?= $resCocktail['description'];?></p> </li>
        <li>Année de conception<?= $resCocktail['dateConception'];?></li>
        <li>Prix <?= $resCocktail['prixMoyen'];?></li>
    </ul>
    <h2>La liste des ingrédients </h2>
    <ul>
        <?php foreach($ingretients as $ingredient){?>
            <li> <?= $ingredient['nom'];?></li> <?php } ?>
    </ul>

   
</body>
</html>