

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="www/css/cocktails.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Mister Cocktail</title>
</head>
<body class="container-fluid">
    <nav>
        <a href="index.php">Accueil</a>
        <h1>Mister Cocktail</h1>
    </nav>
<main>
  <div class="album py-5 bg-light">
    <div class="container">         
      <div class="row">            
      <?php foreach($resCocktails as $cocktail){?>
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <a href="details_cocktail.php?id=<?= $cocktail['id']?>">
            <img class="card-img-top" src="www/images/cocktails/<?php echo $cocktail['urlPhoto'];?>" alt="Card image cap">
          </a>        
            <div class="card-body ">
                <h5 class="card-title text-info"><?php echo $cocktail['nom'];?></h5>
                <p class="card-text"><?php echo $cocktail['description'];?></p>                  
            </div>
        </div>
      </div>
      <?php }?>                 
      </div>
    </div>
  </div>
</main>
</body>
</html>