<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mister Cocktail</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:300,400">
    <link rel="stylesheet" href="www/css/cocktails.css">
</head>
<body class="container-fluid">
    <nav>
        <a href="index.php">Accueil</a>
        <a href="ajout_cocktail.php">Ajouter un cocktail</a>
        <a href="back_office.php">Back-office</a>
        <h1>Mister Cocktail</h1>
    </nav>

    <main>
        <!-- La variable $cocktails vient d'index.php qui a stocké les données de la base SQL dans cette variable -->
        <?php foreach($cocktails as $cocktail): ?>
            <article class="card cocktail">
                <a href="details_cocktail.php?id=<?= $cocktail['id'] ?>">
                    <img class="card-img-top" src="www/images/cocktails/<?= $cocktail['urlPhoto'] ?>" alt="<?= $cocktail['description'] ?>">
                </a>
                <div class="card-body">
                    <h4 class="card-title"><?= $cocktail['nom'] ?></h4>
                    <p class="card-text"><?= $cocktail['description'] ?></p>
                </div>
            </article>
        <?php endforeach; ?>
    </main>
</body>
</html>